server:
  port: 8081

spring:
  datasource:
    mysql:
      jdbc-url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
      password: BTy2523430
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
    psql:
      jdbc-url: jdbc:postgresql://localhost:5432/test?serverTimezone=GMT%2B8&useSSL=false
      username: postgres
      password: BTy2523430
      driver-class-name: org.postgresql.Driver


# 多数据源，这里配置没用，必须在每个数据源配置类里单独配置
#mybatis:
#  configuration:
#    map-underscore-to-camel-case: true
#  mapper-locations: classpath:mapper/*.xml


